### ISSUE TITLE
Using the skip back button always skips to the previous track

### ISSUE THREAD

**Issue by chvp** [accentor/android#184]
It should instead restart the current track, if it has progressed far enough. Blocked on https://github.com/google/ExoPlayer/issues/9084.

**Comment by robbevp** [comment]
This issue also causes the previous button to do nothing on the first track of a playlist

**Comment by chvp** [comment]
Yeah, since there is no previous track to skip to. The good news is that my pull request has been accepted (https://github.com/google/ExoPlayer/pull/9119) so we just need to wait for the next release of ExoPlayer.

**Comment by chvp** [comment]
ExoPlayer 2.14.2 only partially fixed it, sadly. It still doesn't work on  the first track. I'm just going to work around it tomorrow.
