### ISSUE TITLE
Retry GET http requests if they failed

### ISSUE THREAD

**Issue by robbevp** [accentor/android#187]
**Is your feature request related to a problem? Please describe.**
I'm often annoyed when I want to play a new album, wait for the sync to finish only for the album not to play.
This has two causes: 
* ~~The user is not notified when the sync was not successful~~
* Sync seems to fail easily

**Describe the solution you'd like**
Two suggestions
* Try to fetch a page a few times (as we do in web)
* ~~Add fetch items to the local DB, even if the fetch failed. (Since new things come first, they have a high chance of being added)~~

**Comment by chvp** [comment]
Changed the title to reflect #329 being merged
