### ISSUE TITLE
Display sync status

### ISSUE THREAD

**Issue by robbevp** [accentor/android#188]
**Is your feature request related to a problem? Please describe.**
re #187 
The other side of this issue, is that a user can only when syncing, but not know anything about the status.

**Describe the solution you'd like**
Two options that I see:
* Display an error message after a sync failed
* Display the status of the sync somewhere in the UI: ie. 'Currently synchronising' / 'Last succesfull sync: '

**Comment by chvp** [comment]
Last (successful) sync was definitely something I was planning to show in the settings. Same for showing the error on failure.
