### ISSUE TITLE
Long album titles break album view

### ISSUE THREAD

**Issue by robbevp** [accentor/android#221]
##### Reproduction steps

  1. Go to Album view for album with extremely long title
  2. Notice how the title uses more height than cover art.

##### Expected behaviour
We should probably truncate the album title? There are only a few albums which have more than 100ch titles.
It might album be an idea to lower the font-size of the title, so that less titles will cause issues

**Comment by chvp** [comment]
Truncating is definitely possible, but then there is no place where one can see the full album title in the app. Not necessarily a problem, but something to think about.
