### ISSUE TITLE
Ordering of tracks on artist view is confusing

### ISSUE THREAD

**Issue by robbevp** [accentor/android#280]
I find myself confused by the ordering of tracks again and again. Every so often, I have to think and figure out why I see the tracks of an artist in this specific order.

Tracks on an artist view are currently ordered by their album (a-z) and their tracknr (I think). While I get this is the same order 
as the web interface, I don't think this order makes much sense here because:
1. A user can't see the album name in the list or can't see how the tracks are ordered. (And thus, just has to know that this is the ways the tracks are ordered - but I seem to forget this every so often)

2. The ordering IMO isn't useful to the user. If I visit an artist page, I either want to (1) listen to an album or (2) listen to a specific track. 
  If I want to listen to the album, I'll find that in the album list.
  If I want to listen to a track, I currently have to know what album it is on, and how that relates to all other albums discography (and in case of large albums, also know where in the album the track is placed)

## Proposed solution
I can see two options:
1. Order the track A-Z (possible with the album name as a 2nd or 3rd sorting param). This is my prefered option: I you want to listen to track x by a certain artist, you can find that without knowing anything about that artist's albums.
2. Order the tracks by album, but order the albums the same as the albumlist above. This way a user can relate the two pieces of information . I'm undecided whether it would be better to sort the albums A-Z or by release

**Comment by chvp** [comment]
I've noticed this as well, I'll try ordering A-Z and make a release. We can revisit if it doesn't really work.
