### ISSUE TITLE
Home page isn't reactive

### ISSUE THREAD

**Issue by robbevp** [accentor/android#325]
Not sure how possible this is, but it would improve the user experience.

##### Reproduction steps
There are a few ways to notice this:
* play a track while keeping the home page open, notice how 'Recently played albums/artists' doesn't update.
* play a track/album on another device/client -> refresh data -> notice how 'Recently played albums/artists' doesn't update.
* add a new album/artist to database -> refresh data -> notice how 'Recently played albums/artists' doesn't update.

##### Expected behaviour
While those first two are minor/less noticable, the last one oftem causes me confusion or irritation. I know that a new album should have been added, but don't know whether it was added or the refresh failed until I go to another view and back to home

I expect the home page to be reactive and update when the database gets updated. (Or at least after refreshing succeeds).

**Comment by chvp** [comment]
Yeah, I've noticed this is well. It should actually work so not sure what's going on. I was going to look into it this weekend.
