### ISSUE TITLE
 Bottom bar still overlaps main view sometimes

### ISSUE THREAD

**Issue by robbevp** [accentor/android#56]
The last two cards in are never fully visible, but are partially hidden by the player

**Comment by charvp** [comment]
Are you sure you're on the latest version? This is the same issue as #36 and was fixed in #44. It doesn't happen for me, as you can see in the screenshot below.
![Screenshot_20200511-202234](https://user-images.githubusercontent.com/42220376/81597076-65900880-93c5-11ea-95ee-597634ddeac8.jpg)

**Comment by robbevp** [comment]
Oh, you're right, somehow i wasn't on the last version

**Comment by robbevp** [comment]
Reopening this since I get this even in the lastest version.
I get the same view on first start, but after a bit ofuse and switching back and forth with other apps, the main view is covered again.

**Comment by charvp** [comment]
Figured this out. The issue reappears after opening the bottom bar and closing it again.
